# Generated by Django 5.1.3 on 2025-12-10 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_category_slug_and_more'),
        ('users', '0002_remove_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarked_articles',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followed_categories',
            field=models.ManyToManyField(blank=True, to='articles.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followed_tags',
            field=models.ManyToManyField(blank=True, to='articles.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='viewed_articles',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', through='articles.ArticleView', to='articles.article'),
        ),
    ]
