# Generated by Django 5.1.3 on 2025-12-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_tags_alter_region_belongs_to'),
        ('users', '0003_alter_user_bookmarked_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(blank=True, to='articles.article', verbose_name='Written Articles'),
        ),
    ]
