# Generated by Django 5.1.3 on 2025-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_author_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('o', 'Other'), ('u', 'Unknown')], default='u', max_length=1, verbose_name='Gender'),
        ),
    ]
