# Generated by Django 5.1.3 on 2025-12-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_cover_image'),
        ('users', '0006_rename_location_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='authors', to='articles.article', verbose_name='Written Articles'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='profile_image',
            field=models.ImageField(upload_to='editor_profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/', verbose_name='Profile Picture'),
        ),
    ]
