# Generated by Django 5.1.3 on 2025-12-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_articleview_time_articlebookmark'),
        ('users', '0007_alter_author_articles_alter_author_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmarked_articles'
        ),
        migrations.AddField(
            model_name='user',
            name='bookmarked_articles',
            field=models.ManyToManyField(related_name='bookmarked_by', through='articles.ArticleBookmark', to='articles.article'),
        ),
    ]
