# Generated by Django 5.1.3 on 2025-12-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_bookmarked_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='viewed_articles',
        ),
    ]
