# Generated by Django 5.1.3 on 2025-12-10 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_tags_alter_region_belongs_to'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='posts.comment', verbose_name='Parent Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='referenced_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.article', verbose_name='Referenced Article'),
        ),
        migrations.AlterField(
            model_name='post',
            name='referenced_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='posts.post', verbose_name='Referenced Post'),
        ),
    ]
