# Generated by Django 5.1.3 on 2025-12-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='post_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='icon',
            field=models.ImageField(upload_to='reaction_icons/', verbose_name='Icon'),
        ),
    ]
