# Generated by Django 5.1.3 on 2025-12-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postimage_image_alter_reaction_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='rank',
            field=models.IntegerField(default=-1, verbose_name='Rank of Image in Post'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post', verbose_name='Post'),
        ),
    ]
