# Generated by Django 5.1.3 on 2025-12-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postimage_rank_alter_postimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
