# Generated by Django 5.1.3 on 2025-12-07 14:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('news', 'News Article'), ('opinion', 'Opinion'), ('column', 'Column'), ('analysis', 'Analysis')], max_length=50, verbose_name='Article Type')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Writing Time')),
                ('published_at', models.DateTimeField(verbose_name='Publication Time')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField()),
                ('summary', models.TextField(verbose_name='Summary')),
                ('status', models.CharField(choices=[('d-in-progress', 'Draft In Progress'), ('d-completed', 'Draft Completed'), ('in-review', 'In Review'), ('published', 'Published')], default='d-in-progress', max_length=50, verbose_name='Status')),
                ('cover_image', models.FileField(upload_to='', verbose_name='Cover Image')),
                ('requires_premium', models.BooleanField(default=False, verbose_name='Requires Premium')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='View Time')),
                ('duration_seconds', models.IntegerField(verbose_name='View Duration In Seconds')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='EditTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Task Title')),
                ('description', models.TextField(verbose_name='Task Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Edit Creation Time')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('completed_at', models.DateTimeField(verbose_name='Completion Time')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='Slug')),
            ],
        ),
    ]
