# Generated by Django 5.1.3 on 2025-12-07 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editors',
            field=models.ManyToManyField(to='users.editor', verbose_name='Editor'),
        ),
        migrations.AddField(
            model_name='articlereaction',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='articles.article', verbose_name='Reacted Article'),
        ),
        migrations.AddField(
            model_name='articlereaction',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.reaction', verbose_name='Reaction'),
        ),
        migrations.AddField(
            model_name='articlereaction',
            name='reaction_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Reacting User'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Viewed Article'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Viewing User'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category', verbose_name='Parent Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='articles.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='edittask',
            name='assigned_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='users.editor', verbose_name='Assigned Editor'),
        ),
        migrations.AddField(
            model_name='edittask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='users.editor', verbose_name='Task Creator Editor'),
        ),
        migrations.AddField(
            model_name='edittask',
            name='edited_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_tasks', to='articles.article', verbose_name='Edited Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='articles.tag', verbose_name='Tag'),
        ),
        migrations.AddConstraint(
            model_name='articlereaction',
            constraint=models.UniqueConstraint(fields=('article', 'reaction_owner'), name='unique_user_reaction_per_article'),
        ),
        migrations.AddConstraint(
            model_name='edittask',
            constraint=models.UniqueConstraint(fields=('edited_article', 'title'), name='unique_edit_task_title_per_article'),
        ),
    ]
