# Generated by Django 5.1.3 on 2025-12-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='regions',
            field=models.ManyToManyField(to='articles.region', verbose_name='Region'),
        ),
    ]
