# Generated by Django 5.1.3 on 2025-12-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_region_article_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belonging_regions', to='articles.region', verbose_name='Belongs To'),
        ),
    ]
