# Generated by Django 5.1.3 on 2025-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_region_belongs_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='region',
            name='belongs_to',
            field=models.ManyToManyField(related_name='belonging_regions', to='articles.region', verbose_name='Belongs To'),
        ),
    ]
