# Generated by Django 5.1.3 on 2025-12-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_region_belongs_to_region_belongs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='priority_level',
            field=models.IntegerField(choices=[(3, 'Breaking'), (2, 'High Priority'), (1, 'Important'), (0, 'Normal')], default=0, verbose_name='Priority Level'),
        ),
        migrations.AlterField(
            model_name='region',
            name='belongs_to',
            field=models.ManyToManyField(blank=True, related_name='belonging_regions', to='articles.region', verbose_name='Belongs To'),
        ),
    ]
