# Generated by Django 5.1.3 on 2025-12-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='region',
            name='belongs_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='belonging_regions', to='articles.region', verbose_name='Belongs To'),
        ),
    ]
