# Generated by Django 5.1.3 on 2025-12-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_tags_alter_region_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(upload_to='', verbose_name='Cover Image'),
        ),
    ]
