# Generated by Django 5.1.3 on 2025-12-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('news', 'News Article'), ('opinion', 'Opinion'), ('analysis', 'Analysis')], max_length=50, verbose_name='Article Type'),
        ),
    ]
