# Generated by Django 5.1.3 on 2025-12-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_articleview_duration_seconds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleview',
            old_name='time',
            new_name='created_at',
        ),
    ]
