# Generated by Django 5.1.3 on 2025-12-22 10:02

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_rename_time_articleview_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-trending_score']},
        ),
        migrations.RemoveField(
            model_name='articlebookmark',
            name='time',
        ),
        migrations.AddField(
            model_name='article',
            name='trending_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='articlebookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Bookmarked At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlereaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Reacted At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Viewed At'),
        ),
        migrations.AddConstraint(
            model_name='articlebookmark',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_bookmarking_user_per_article'),
        ),
    ]
