# Generated by Django 5.1.3 on 2025-12-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_article_options_remove_articlebookmark_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editorial_heat_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
