# Generated by Django 5.1.3 on 2025-12-25 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_article_editorial_heat_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='articleview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to=settings.AUTH_USER_MODEL, verbose_name='Viewing User'),
        ),
    ]
